dist: trusty
sudo: required
language: python

matrix:
  include:
    - name: "Python 3.5"
      env: PY_VERSION=py35
    - name: "Python 3.6"
      env: PY_VERSION=py36
    - name: "Python 3.7"
      env: PY_VERSION=py37
    - name: "Python 3.8"
      env: PY_VERSION=py38

services:
  - docker

before_install:
  - sudo apt-get update && sudo apt-get install -y make

script:
  - make test-$PY_VERSION

notifications:
  email: false
